### PR TITLE
Router store diagram

### PR DESCRIPTION
**Pull request by Jefiozie**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?
Adds a diagram for the flow of actions within the router store

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

@timdeschryver here is the PR for the diagram, I merged my branch with the changes for the action creators. This because I made changes to the docs there, I think this should be merged before this one is merged #2272

### CODE REVIEW

**Comment by Jefiozie** [comment]
Sure thing, I did it on purposes as I also changed some stuff in the other PR that is a little bit related to this one.

**Comment by Jefiozie** [comment]
@timdeschryver done 😄

**Comment by timdeschryver** [comment]
Pinging @brandonroberts @wesleygrimes @jordanpowell88 since ya'll were involved for the action flow diagram.

**Comment by wesleygrimes** [comment]
I would love to see this match the diagram font and colors that @jordanpowell88 did. Jordan did you ever upload the PSD and/or AI files?

**Comment by Jefiozie** [comment]
Sure, if there are some assets that I can use for that I can change it

**Comment by jordanpowell88** [comment]
@wesleygrimes @Jefiozie @timdeschryver I would be happy to upload the psd file. Where would you like for me to put it?

**Comment by Jefiozie** [comment]
If there is a need to have like a default kit for people to use, I would say let's make a "Press Kit" available via the `ngrx.io` site. 

If you can share it via wetransfer of any other way I'm totally fine with it.

**Comment by jordanpowell88** [comment]
Do we want to put the PSD file directly in a "Press Kit" folder in the repository? Or do we want to just link to an external download like a CDN or some other file sharing service? If that is the case is their something like this already set up? @timdeschryver

**Comment by Jefiozie** [comment]
I've not yet found something like this for the ngrx site. Maybe we can start by sharing the psd so that we can create the diagram?(or maybe you can recreate the diagram and share the png).

I can create a issue to create a press kit page on the ngrx site? (And maybe even make it 😁)

**Comment by brandonroberts** [comment]
A press kit page that includes the diagrams would be great.

**Comment by brandonroberts** [comment]
Now that #2296 has landed, you can add the diagram to that page.

**Comment by brandonroberts** [comment]
Reopen this when you're ready.

**Pull request closed without merging**
