### PR TITLE
docs(home): improve responsiveness on the home page for small screens

### LINKED ISSUE #1866: Docs: home page isn't responsive on some mobile screens
## Other information:

Texts are cropped and aligned to the right at the home page of the documentation app for some mobile screens.

Reported on:

- Huawei P20 Lite
- iPhone XS Max
- Samsung Galaxy S5 (Chrome Dev Tools)
- iPhone5 (Chrome Dev Tools)
- iPhone6/7/8 (Chrome Dev Tools)

There is a similar issue that was closed: #1536

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by NachoVazquez**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #1866

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

* Screenshots before and after the changes were created.

### CODE REVIEW

**Comment by NachoVazquez** [comment]
Any suggestions on how can I replicate the Issue?

I already tried in `Chrome` and `Firefox` and it looks ok for the iPhone X/XS.

It seems a vendor issue. I'm using:
- viewport units which are compatible with Safari > 6.1
- flexbox which is compatible with Safari > 6.1
- overflow which is partially compatible with Safari. In particular, Does not support the two value overflow shorthand. This could be the issue, I'm using overflow-x.

I'll update in a minute changing overflow-x with just overflow.

**Comment by wesleygrimes** [comment]
Yes unfortunately the device simulation (and even emulators) doesn't always get it right. If I look on the chrome simulator it looks correct on my computer, but as soon as I try on my phone it's overflowing. Wonder if we could make use of Browserstack or Saucelabs or something like that?

**Comment by NachoVazquez** [comment]
I believe that it's fixed now, but I can't test it because the preview wasn't created correctly.

Please, when you have a time restart the build process and test if it's fixed.

When I get the email of the preview creation, I'll check too.

**Comment by wesleygrimes** [comment]
Unfortunately still running off the edge on my iPhone XS Max.

**Comment by NachoVazquez** [comment]
Safari is killing me, now it fits ok in the screen but the `font-size` is smaller than the other code example.

It's only happening on Safari. It looks ok in Chrome and Android Chrome.

Let me know what do you think about it.  I'll try to fix it, but again I have no way to replicate the issue.

**Comment by brandonroberts** [comment]
Thanks @NachoVazquez!

**Comment by NachoVazquez** [comment]
Your welcome @brandonroberts!! You have given me more than what I could repay.

Expect my full cooperation and let me know if you need anything in particular.

**Pull request merged**
