### PR TITLE
DevTools Sanitizer Service and allow Devtool Options to be injectable

### PR DESCRIPTION
**Pull request by phillipzada**
Hi team,

Created a DevTools sanitizer service that allows for multiple (or single) sanitizers to be injectable. This provides an avenue to address #825 

I've also exposed the DevTools Options to be injectable via a provider.

Thanks
Phill

### CODE REVIEW

**Comment by dummdidumm** [comment]
In what way does it adress the issue? DevTools already have a action/state sanitizer. What is the advantage of having them injectable and provided via tokens?

**Comment by phillipzada** [comment]
Hey @dummdidumm, We've had the use case with lazy loaded modules (eg. Nrwl NX Framework) where we need sanitizers added to handle specific cases. whereas the current sanitizer is for a single action/state santizier this option gives the ability to register multiple.

**Comment by cbeall** [comment]
This has been sitting for a while and appears it has a few conflicts at this point, but I agree that including it would be valuable. Using DI would allow for clean separation of concerns, and the current implementation really presents complications with regard to lazy loading. 

Are there an updates here?

**Comment by brandonroberts** [comment]
@cbeall at a minimum I'd like to see the configuration tokens be exposed. I think the custom sanitizer service should be left out for now. Or added as a recipe in the docs. Would you want to put in a PR for that part?

**Comment by phillipzada** [comment]
@brandonroberts happy to put a PR and start it again from a newer codebase. Let me know if there is anything else you would like to see other than exposed DI tokens.

**Comment by brandonroberts** [comment]
@phillipzada thanks Phillip. If you want to add a recipe to the docs about using a custom sanitizer that would be great.

**Comment by brandonroberts** [comment]
Going to close this one. Open a new PR for the changes we talked about.

**Pull request closed without merging**
