### PR TITLE
feat(store-devtools): pass entire error object to the error handler

### LINKED ISSUE #2824: RFC: Error object to be passed to the error handler instead of error stack string
## Describe any alternatives/workarounds you're currently using

I am wondering about the reason why `error.stack` is [passed](https://github.com/ngrx/platform/blob/10.1.x/modules/store-devtools/src/reducer.ts#L75) to the error handler instead of entire `error`.

My use case is that I want to handle all script errors and get an `error.message` string to be show in the notification. Below example of custom error handler:
```ts
...
export class CustomErrorHandlerService extends ErrorHandler {
   ...
   handleError(error: any): void {
       if (error instanceof Error) {
           // service consume entire "error" object to get a "message" and "stack" for own needs
           this.scriptErrorHandler.handle(error); 
       }

       super.handleError(error);
   }
}
```

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by r0ss0neri**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #2824

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]
Changes LGTM but I'd consider it a breaking change that we need to add to the migration guide

**Review by timdeschryver — COMMENTED** [review]
You can find the migration guide [here](https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/guide/migration/v11.md). Are you going to add a note here @r0ss0neri ?

**Review by timdeschryver — APPROVED** [review]
I'll merge this and add a note to the migrations.

**Comment by r0ss0neri** [comment]
> I'll merge this and add a note to the migrations.

@timdeschryver thank you!

**Pull request merged**
