### PR TITLE
feat(Codegen): Add base code and build for @ngrx/codegen

### PR DESCRIPTION
**Pull request by MikeRyanDev**
Includes basic implementation for the [@ngrx/codegen proposal](https://paper.dropbox.com/doc/ngrxcodegen-Proposal-DhD934mmHfqTljpntnqJ3)

### CODE REVIEW

**Comment by bmayen** [comment]
Why not devkit schematics for this?

**Comment by MikeRyanDev** [comment]
@bmayen Why would you suggest schematics? Genuinely curious.

**Comment by bmayen** [comment]
Primarily because a) it already exists to handle code generation, and b) would give us a single workflow when using something like Angular CLI. 

In the same way that Angular provides a set of schematics which CLI consumes, so could ngrx. Then organizations, which may have customization needs, have an easy way to extend the defaults.

Also, over time, schematics looks like it will become more powerful; supporting user prompting, for instance. Would be nice to be able to leverage this without having to develop and maintain similar functionality in parallel.

**Comment by mko** [comment]
I agree that having an `@ngrx/cli` which provides similar functionality to the schematics of `@angular/cli` would likely be a better long-term strategy than codegen, but this might be a good starting point in the interim.

**Comment by MikeRyanDev** [comment]
We'll explore how to integrate this tool with Schematics. Merging early to start producing nightly builds.

**Comment by bmayen** [comment]
Sounds good! Let me know if I can help with any Schematics effort.

**Pull request merged**
