### PR TITLE
chore: add script to update package.json versions

### LINKED ISSUE #2562: Schematics: set default install version to 10.x
## Describe any alternatives/workarounds you're currently using

Update the install version to version 10 for the ng-add packages

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### LINKED ISSUE #2563: Build: Add schematic to update version numbers for release
## Describe any alternatives/workarounds you're currently using

Each package has a `version` in its `package.json`. This schematic would update the versions to align on the same number based on an input to the schematic. This would be run along with changelog generation.

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by timdeschryver**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #2563 
Closes #2562
Partially #2557

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by timdeschryver** [comment]
Is this what you had in mind for #2563 @brandonroberts ?
If not feel free to close it, otherwise I think we can expand this script to update more version files (#2563, #2557, #2562)

**Comment by brandonroberts** [comment]
@timdeschryver Yep, this is what I had in mind. Just something to bump the versions across the packages before release. We wouldn't need it for the docs, as its based off the label I think. We would need it after we move away from the docs app though.

**Comment by timdeschryver** [comment]
For the docs I meant that it could add the earlier version to the versions - https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/navigation.json#L507

**Comment by brandonroberts** [comment]
I see. We only update that one for major releases, but yea

**Comment by timdeschryver** [comment]
👍 I will probably add more later this week.

**Comment by timdeschryver** [comment]
@brandonroberts should be good to go on my end, if there's something that you think of that can be added you can let me know and I'll add it.

I didn't run the script as I'm assuming that we'll cut a RC/beta first.

To run it, use

```
yarn update:versions 10.0.0-rc.0
# or just
yarn update:versions 
```

**Pull request merged**
