### PR TITLE
feat(StoreDevtools): implement actionsBlacklist/Whitelist & predicate

### PR DESCRIPTION
**Pull request by Wykks**
Ref: #938 

Note: the unit tests doesn't test jump / slider (I'm not sure how to test that).

There an issue when using the slider (and the action filter feature).
The app doesn't get the right state (whereas the extension show the correct state).
To reproduce in the example app, add `actionsBlacklist`:
```
    StoreDevtoolsModule.instrument({
      name: 'NgRx Book Store DevTools',
      logOnly: environment.production,
      actionsBlacklist: ['\\[Book\\] Search$']
    }),
```
Do two different search, then, jump or slide back to the previous `Search Complete`.

Sorry for leaving this issue here, I spend more than half a day figuring out how this works... This is as far as I'm able to do, for now... I'll try to investigate more If needed, but you probably already know what's going on :sweat_smile:

Edit: Ok I see what's going on. Since I filter the `liftedState` only for the `devtoolsExtension.send`, the `currentStateIndex` send by the extension is desync with the internal `liftedState`.

I could actually filter-out the state outside `extension.notify` but according to: https://github.com/zalmoxisus/redux-devtools-extension/issues/316#issuecomment-283914716 , the internal `liftedState` should not be filtered.

Edit 2 : Welp, I guess I should filter the state outside `extension.notify` after all. It works fine. But I'm a bit puzzled about how to "properly" code this. I'll update the PR next time (maybe tomorow).

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks for the PR @Wykks! As an alternative, I'm looking into sending all actions/states through the extension since it already has support for blacklist/whitelist/predicate and I don't think we need to duplicate all that on our end.

**Comment by kevinahuber** [comment]
Any word/work on this? Happy to help get this through.

**Comment by Wykks** [comment]
Hi!

Sorry for this very long silence... I totally got demoralized doing this PR.
I can't help thinking that something is really wrong.

Just like Brandon said, this should be handled by the extension itself. But it doesn't work when sending the full state (with `this.devtoolsExtension.send`); because the extension doesn't filter anything in this case. That's why I started to handle both cases.

But, I really don't get why it's implemented like that in the extension. This should just be a visual thing, with some skip when moving through states. There's no actual need to filter the state like that...

**Comment by brandonroberts** [comment]
@Wykks apologies for getting behind on this one. Will you rebase on master? Handling it here may be the option for now. We may need to open an issue on the extension to at least get some clarification on filtering when full state is provided.

**Comment by brandonroberts** [comment]
@Wykks will you rebase this one?

**Comment by Wykks** [comment]
ops didn't saw the last message. I can do the rebase this week yep!

**Comment by brandonroberts** [comment]
👍

**Comment by Wykks** [comment]
Rebased and updated!
Same thought on this stuff since the last time I spent time on it; it doesn't feel correct but it works.

**Comment by brandonroberts** [comment]
@Wykks will you rebase again? Thanks

**Comment by Wykks** [comment]
Done, sorry for the delay..

**Comment by brandonroberts** [comment]
🎉

**Comment by wendelstam** [comment]
Really nice addition. In what version will this be included in the NPM package?

**Comment by timdeschryver** [comment]
It will become available in the next version (7).
You can use it now by using the nightly builds.

**Pull request merged**
