### PR TITLE
refactor(schematics): change default value of minimal to true

### LINKED ISSUE #2251: Effects: Use minimal option by default for ng add
Change minimal to be `true` by default, so only the `Effects.forRoot([])` is added to the AppModule.

The option is here: https://github.com/ngrx/platform/blob/master/modules/effects/schematics/ng-add/schema.json#L52

### PR DESCRIPTION
**Pull request by ilyaryabchinski**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
default value of  minimal is false

Closes #2251

## What is the new behavior?
default value of  minimal is true

## Does this PR introduce a breaking change?

```
[x ] Yes
[ ] No
```

### Breaking change

Before:
When adding effects using schematics minimal flag by default was false.

After:
When adding effects using schematics minimal flag by default is true.

### CODE REVIEW

**Comment by ilyaryabchinski** [comment]
@brandonroberts Hi!
Is this MR okay? or something more is needed ?

**Comment by ilyaryabchinski** [comment]
done

**Comment by ilyaryabchinski** [comment]
Thanks for your help!

**Comment by timdeschryver** [comment]
@ilyaryabchinski could you also add a breaking change note to the PR please, you can find a template in [CONTRIBUTING.MD](https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#footer)

**Comment by ilyaryabchinski** [comment]
@timdeschryver done :)

**Pull request merged**
