### PR TITLE
RFC: Schematics: Extend from @schematics/angular #882

### PR DESCRIPTION
**Pull request by MichaelWarneke**
Inherit the ngrx schematics from angular schematics.

The angular devkit has been updated to allow extends.
[angular/devkit#34](https://github.com/angular/devkit/issues/34)

By inheriting the hole package instead of some individual generators reduces boiler plate in the collection.json and makes sure that future angular generators are included automatically.

### CODE REVIEW

**Comment by brandonroberts** [comment]
This would require a minimum version of the CLI with the devkit dependency correct?

**Comment by MichaelWarneke** [comment]
Yes. The extends property got merged into devkit version 0.3.1 which got merged into angular cli 1.7.0-rc.0.
[merged into cli](https://github.com/angular/angular-cli/commit/57d7c165705fe81344e9d0f5c2b1df78bc77c3ef)

**Comment by brandonroberts** [comment]
@MichaelWarneke can you add the following peer dependencies to the `package.json` for schematics to ensure there a minimum version that supports this for V6?

```
"@angular-devkit/core": "^0.4.0",
"@angular-devkit/schematics": "^0.4.0"
```

**Comment by MichaelWarneke** [comment]
Done

**Comment by MikeRyanDev** [comment]
Merged into next. Thanks!

:clap: :clap: :clap:

**Pull request closed without merging**
