### PR TITLE
docs: make runtime checks' header sections consistent

### PR DESCRIPTION
**Pull request by rafaelss95**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
A small inconsistent in runtime checks docs:

Captura de Tela 2020-08-22 às 19 09 42

### CODE REVIEW

**Comment by rafaelss95** [comment]
@timdeschryver Ah, I almost forgot to say, but I noticed that the @ngrxbot is always generating an incorrect endpoint, which redirects to a 404 route.

**Comment by timdeschryver** [comment]
It takes a couple of minutes to be deployed. Once a PR is closed, we also remove the release. That's why it's now a 404. 

Also keep in mind that the preview is only available from its root.

**Comment by rafaelss95** [comment]
Hmm, idk... but I noticed it yesterday, a few minutes after the @ngrxbot comment.

**Comment by timdeschryver** [comment]
Thanks @rafaelss95 we'll keep an eye on it next time.

**Pull request merged**
