### PR TITLE
docs(signals): update stackblitz link

### PR DESCRIPTION
**Pull request by rainerhahnekamp**
This links the current (and outdated) Stackblitz template for the Signal Store to a GitHub repo, which is much easier to update.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by brandonroberts** [comment]
I would suggest we create a `signal-store-starter` repository under the ngrx org and point to that

**Comment by brandonroberts** [comment]
> @brandonroberts, that's even better.
> 
> Maybe we create starters for the global and the component store as well?
> 
> Do you create the repos or should I do it?

Good idea. You can create the repos. Let me know if you can't for some reason.

**Comment by markostanimirovic** [comment]
any update on this? 👀 it would be great if we could provide the v18 playground soon.

**Comment by rainerhahnekamp** [comment]
Yes, got just moved in my list

**Review by brandonroberts — APPROVED** [review]

**Review by markostanimirovic — APPROVED** [review]

**Pull request merged**
