### PR TITLE
refactor(example-app): Update logger metareducer

### PR DESCRIPTION
**Pull request by cmckni3**
* Use collapsed console group in logger metareducer

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] Other... Please describe:

Example app refactoring
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Shows dispatched action and state in a collapsed `console.group`

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by cmckni3** [comment]
I have not confirmed it in all browsers but according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Console/groupCollapsed#Browser_compatibility) it has support in IE 11, Edge 12+, and Safari 5.1+.

I have confirmed it works in Chrome 68, Firefox 63, Safari 11.1.2.

Maybe there should be a note about it may not work? FWIW, I wouldn't recommend using the logger metareducer in production builds.

**Comment by brandonroberts** [comment]
I only ask because we've gotten issues before about the example app not working in IE, but I think that's sufficient coverage.

**Comment by brandonroberts** [comment]
Thanks @cmckni3!

**Comment by cmckni3** [comment]
No problem!

**Pull request merged**
