### PR TITLE
Add note about actions and effects for router usage

### PR DESCRIPTION
**Pull request by glendaviesnz**
Could be useful to have the details about how to set up router actions and effects included on router docs page - currently only in the migration guide

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks for the PR @glendaviesnz! I would rather this be added as a separate section under API Documentation

**Comment by glendaviesnz** [comment]
@brandonroberts  - no worries - will try and update PR later today

**Comment by glendaviesnz** [comment]
@brandonroberts finally go back to do this - action and effects details moved to api section

**Comment by brandonroberts** [comment]
Thanks!

**Pull request merged**
