### PR TITLE
add example using Angular 6

### PR DESCRIPTION
**Pull request by ngohungphuc**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ X ] Other... Please describe: Add example
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[ ] Yes
[ x ] No
```

### CODE REVIEW

**Comment by ngohungphuc** [comment]
Any updated yet ?

**Comment by brandonroberts** [comment]
Thanks for the PR @ngohungphuc! I'm not sure this belongs here as the example app is already using Angular 6 and an authentication example. Why do you want to add this additional example?

**Comment by ngohungphuc** [comment]
Hi @brandonroberts It's just a simple login example for everyone don't have any experience with Ngrx will likely easy to get start.

**Comment by timdeschryver** [comment]
What about adding a section "Build with NgRx" or "Community example projects" on ngrx.io?
I think it will be hard to maintain different example apps in this repository.

**Comment by ngohungphuc** [comment]
I agree on the part add a section name: Community example projects. Would that be ok @brandonroberts

**Comment by ngohungphuc** [comment]
Hi.
Any update guys ?

**Comment by ngohungphuc** [comment]
@timdeschryver @brandonroberts Hi guys.
Is there any update ?

**Comment by timdeschryver** [comment]
Hi @ngohungphuc we're all a bit busy, please be patient.
I'm sure Brandon will respond to this when he has the time.

**Comment by timdeschryver** [comment]
Hi, I'm going to close this PR because we're going to create a community page, please feel free to add your project to https://github.com/ngrx/platform/issues/1411.

**Pull request closed without merging**
