### PR TITLE
chore: use pull_request_target in PR labeler

### PR DESCRIPTION
**Pull request by cedricduffournet**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Other information
PR labeler doc: https://github.com/actions/labeler/tree/main#create-workflow
More info about why user pull_request_target: https://github.com/actions/labeler/issues/121

### CODE REVIEW

**Comment by cedricduffournet** [comment]
Not sure if it fix something as PR don't have label from github-actions since years

**Comment by cedricduffournet** [comment]
@brandonroberts is it back to  enable ? https://github.com/ngrx/platform/pull/2899#issuecomment-770123782

**Comment by brandonroberts** [comment]
@cedricduffournet we're not looking re-enable this at the moment

**Comment by cedricduffournet** [comment]
Ok, don't understand why my PRs failed on label github actions https://github.com/ngrx/platform/pull/3683/checks

**Pull request closed without merging**
