### PR TITLE
refactor(effects): replace NotificationKind with a string literal 

### PR DESCRIPTION
**Pull request by timdeschryver**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by born2net** [comment]
what is the best way to remedy this so I can move fwd as I am stuck on this bug...

**Comment by timdeschryver** [comment]
You can install NgRx v8.0.1 @born2net

**Comment by born2net** [comment]
ok great checking TX!

**Comment by born2net** [comment]
worked! TX

**Comment by born2net** [comment]
please close issue TX

**Pull request merged**
