### PR TITLE
fix(component): transform to Observable if Input is Promise

### PR DESCRIPTION
**Pull request by DaSchTour**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Push Pipe breaks if input is a Promise, which means it's not a drop in replacement for async pipe at the moment

Closes #

## What is the new behavior?

If the input is a Promise it is converted to an Observable

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]

**Review by timdeschryver — COMMENTED** [review]
LGTM, I do think that we should add a test to verify this tho.

**Comment by DaSchTour** [comment]
I actually thought, that there are no tests for the components, just now when I wanted to create a test and was searching for other tests I saw, that there is a separate folder with all the specs. That's very different from what I'm used to from all other angular projects.

**Comment by DaSchTour** [comment]
Okay. I'm sorry but I'm out. I have no idea why the test are not working. But I would like to raise the attention, that this is a critical issue, because people that use the async to ngrxPush migration and having Promises will have a bugs that are not visible directly!

**Comment by timdeschryver** [comment]
It seems like I'm not able to push against this branch, so I created #2893 with the fixes to make the tests green.

**Comment by brandonroberts** [comment]
Closed with #2893 with both commits added to preserve the original author's commit

**Comment by timdeschryver** [comment]
Thanks again for fixing this issue @DaSchTour 👍

**Comment by DaSchTour** [comment]
@timdeschryver I'm glad I could help.

**Pull request closed without merging**
