### PR TITLE
fix(store): prevent unexpected behavior of {} as a props type

### PR DESCRIPTION
**Pull request by markostanimirovic**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

```typescript
// Case 1
const foo = createAction('foo', props<{}>()); // no error
foo(1); // no error
foo('1'); // no error

// Case 2
const foo = createAction('foo', props<{ bar?: string }>()); // ok
foo({}); // ok
```

## What is the new behavior?

```typescript
// Case 1
const foo = createAction('foo', props<{}>()); // error
foo(1); // error
foo('1'); // error

// Case 2
const foo = createAction('foo', props<{ bar?: string }>()); // ok
foo({}); // ok
```

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by timdeschryver — CHANGES_REQUESTED** [review]
I think this is looking good! 
@alex-okrushko can you also give this a look please?

@markostanimirovic it is missing a test at https://github.com/markostanimirovic/platform/blob/fix-payload-type/modules/store/spec/types/action_creator.spec.ts#L14, could you add one please?

**Comment by markostanimirovic** [comment]
> I think this is looking good!
> @alex-okrushko can you also give this a look please?
> 
> @markostanimirovic it is missing a test at https://github.com/markostanimirovic/platform/blob/fix-payload-type/modules/store/spec/types/action_creator.spec.ts#L14, could you add one please?

@timdeschryver sure

**Comment by alex-okrushko** [comment]
Hey @markostanimirovic 
Didn't you want to switch it to the `Record<string, unknown>` or something similar?

**Comment by markostanimirovic** [comment]
I think this solution is better for minor/patch release, because with `Record` I should change signatures of multiple methods. But, I could refactor it in this PR. What do you think @alex-okrushko ?

**Comment by alex-okrushko** [comment]
> I should change signatures of multiple methods.
@markostanimirovic 
it shouldn't really change that much - it makes it a bit stricter, right?

**Comment by markostanimirovic** [comment]
@alex-okrushko Yes, `Record` will make the props stricter. Array type will be denied by default and `ArraysAreNotAllowed` branch can be removed from `NotAllowedCheck` type guard, as we discussed.

I'll do that 👍

**Review by timdeschryver — APPROVED** [review]
LGTM, thanks!

**Comment by alex-okrushko** [comment]
> So, it's not compatible with interfaces 👎

@markostanimirovic I'd argue that they shouldn't be compatible with the interfaces 🙂 Maybe that would be a good breaking (separate) change for the v11! (cc @brandonroberts and @timdeschryver ).

### Why?

`props<Foo>()` does **not** make sense, because that `Foo` would be appended with `type` property, e.g.
`const thingHappened = createAction('[source] a thing happened', props<Foo>())` would the `action` to reducer as `Foo & {type: [source] a thing happened}`.

How do you remove it in the reducer?

```ts
// One might even name it as foo 👇 while in fact it's still an action: foo obj + type prop
on(thingHappened, (state, foo) => ({ ... }))
```

if the `foo` is saved that way - you'll get more than you are expecting... and it would show in redux dev tools.
Ideally one would do this:

```ts
on(thingHappened, (state, {type, ...foo}) => ({ ... }))
```

That way type is detached and the actual `foo` is used further, but I doubt many people do that, and, on top that, it would be easier to wrap it with prop at that point in `props`: `props<{foo: Foo}()>` to avoid all of this:

```ts
on(thingHappened, (state, {foo}) => ({ ... }))
```

**Review by alex-okrushko — APPROVED** [review]

**Comment by markostanimirovic** [comment]
> > So, it's not compatible with interfaces 👎
> 
> @markostanimirovic I'd argue that they shouldn't be compatible with the interfaces 🙂 Maybe that would be a good breaking (separate) change for the v11! (cc @brandonroberts and @timdeschryver ).
> 
> ### Why?
> `props<Foo>()` does **not** make sense, because that `Foo` would be appended with `type` property, e.g.
> `const thingHappened = createAction('[source] a thing happened', props<Foo>())` would the `action` to reducer as `Foo & {type: [source] a thing happened}`.
> 
> How do you remove it in the reducer?
> 
> ```ts
> // One might even name it as foo 👇 while in fact it's still an action: foo obj + type prop
> on(thingHappened, (state, foo) => ({ ... }))
> ```
> 
> if the `foo` is saved that way - you'll get more than you are expecting... and it would show in redux dev tools.
> Ideally one would do this:
> 
> ```ts
> on(thingHappened, (state, {type, ...foo}) => ({ ... }))
> ```
> 
> That way type is detached and the actual `foo` is used further, but I doubt many people do that, and, on top that, it would be easier to wrap it with prop at that point in `props`: `props<{foo: Foo}()>` to avoid all of this:
> 
> ```ts
> on(thingHappened, (state, {foo}) => ({ ... }))
> ```

@alex-okrushko Looks good. It will make NGRXers to use the library in the right way 🤘

**Comment by alex-okrushko** [comment]
Btw, this is a breaking change (making it stricter).
cc @brandonroberts

**Pull request merged**
