### PR TITLE
docs: Add issue templates

### PR DESCRIPTION
**Pull request by brandonroberts**
Add some custom issue templates to help with filing issues and requests.

### CODE REVIEW

**Comment by tdeschryver** [comment]
Awesome! 
Would the [StackBlitz ngrx-seed](https://stackblitz.com/edit/ngrx-seed) from #1079 be useful to add?
If it would, I was thinking since there wasn't much response, we could ask if the seed was helpful or if there was something they were missing in it and update the seed accordingly until it is 'perfect'.

**Comment by tdeschryver** [comment]
I've added the store devtools integration. I thought it wouldn't work in StackBlitz, but it does ... StackBlitz never disappoints ✨ 

I also added the logger meta reducer.

This may seem stupid but what do you mean with `counter actions need to be fixed` 😅?
I did rename the action types if this is what you meant.

**Comment by brandonroberts** [comment]
That's what I mean. Couple more things. Remove the "Start edting" line, fix the spacing in `AppModule` imports and Store Devtools name (NgRg) and then I think its set for now.

**Comment by tdeschryver** [comment]
Done, done and done. 
Thanks for the review.

**Pull request merged**
