### PR TITLE
ci(schematics): rename BUILD.bazel to BUILD

### LINKED ISSUE #1816: Rename schematics-core\build.bazel to BUILD
## I would be willing to submit a PR to fix this issue

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by santoshyadav198613**
Fixes #1816

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by santoshyadav198613** [comment]
Hi @timdeschryver ,

I think it was named BUILD.bazel to avoid compiling schematics-core folder as a package.
In case we still want to name it BUILD, we need to remove the core folder from compiling.
https://github.com/ngrx/platform/blob/master/build/config.ts#L23

**Comment by timdeschryver** [comment]
You're probably right 👍
Let's keep this open for @brandonroberts 's confirmation.

**Comment by santoshyadav198613** [comment]
> You're probably right 
> Let's keep this open for @brandonroberts 's confirmation.

Or we can simply remove this file as it is not getting used.

**Comment by brandonroberts** [comment]
Bazel uses BUILD.bazel or BUILD files for compilation. The file is needed to compile the core files for testing.

**Comment by santoshyadav198613** [comment]
> Bazel uses BUILD.bazel or BUILD files for compilation. The file is needed to compile the core files for testing.

Yes but schematics-core folder doesn't use it. We just copy the content from here and build other folders.

**Comment by brandonroberts** [comment]
It's used in test compilation. See https://github.com/ngrx/platform/blob/master/modules/schematics/BUILD. Renaming it seems fine for fixing the script to copy files.

**Pull request closed without merging**
