### PR TITLE
feat(ErrorHandler): use the angular ErrorHandler for reporting errors

### LINKED ISSUE #626: Effect error logging should be customizable or use ErrorHandler
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Errors are sent to the internal `ErrorReporter` which logs to the console

## Expected behavior:
Errors should be logged to `ErrorHandler` (from `@angular/core`) or `ErrorReporter` should be public and customizable/overridable to allow doing so (or both).

## Version of affected browser(s),operating system(s), npm, node and ngrx:
4+ ?

## Other information:
Personally I'd think just sending all errors to `ErrorHandler` would be best and the `ErrorReporter` can  be removed, but maybe others depend on the console logging from `ErrorReporter`? Maybe just making `ErrorReporter` public/overridable is a good start without any breaking changes?

### PR DESCRIPTION
**Pull request by jbedard**
Fixes #626

This is a v5 alternative to #635. Can potentially try to keep `InvalidActionError` and `EffectError` but I'm not sure if that is a standard thing to do with `ErrorHandler`?

BREAKING CHANGE:

Errors are now reported to the @angular/core ErrorHandler.
Errors are no longer reported to the console.

### CODE REVIEW

**Comment by brandonroberts** [comment]
The ErrorHandler reports to the console by default, so it wouldn't be a breaking change.

**Comment by jbedard** [comment]
It is a breaking change if #635 gets released in v4. Shall I remove the breaking change from the commit message though?

**Comment by brandonroberts** [comment]
@jbedard The breaking change should remain, but the format should be altered so it shows in the changelog correctly..

```
BREAKING CHANGE:

BEFORE:

AFTER:
```

**Comment by brandonroberts** [comment]
@jbedard this one is ready to land once the commit message is updated.

**Comment by jbedard** [comment]
I've updated the commit message, and rebased. Let me know if the commit message is ok...

**Comment by brandonroberts** [comment]
LGTM

**Pull request merged**
