### PR TITLE
feat(router-store): add navigation extras in router request action

### LINKED ISSUE #1678: Add NavigationExtras in the router request action
My current objective is to be able to get the list of routes in the application. For now, I can listen to back/forward move with the following: 

```
const routerRequest$ = actions$.pipe(
    ofType<RouterRequestAction>(ROUTER_REQUEST)
);
const routerNavigation$ = actions$.pipe(
    ofType<RouterNavigationAction>(ROUTER_NAVIGATION)
);
const routerNavigated$ = actions$.pipe(
    ofType<RouterNavigatedAction>(ROUTER_NAVIGATED)
);

zip(routerRequest$, routerNavigation$, routerNavigated$).subscribe(([request, _, navigated]) => {
    if (request.payload.event.restoredState) {
        console.log('go back')
        console.log(navigated.payload.event)
    } else {
        console.log('go to')
        console.log(navigated.payload.event)
    }
});
```

But I miss one case with the `replaceUrl` of `NavigationExtras` from `@angular/router` package https://angular.io/api/router/NavigationExtras

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

## Other information

I am not sure how to make it work but I would be glad to submit a PR for that.

### PR DESCRIPTION
**Pull request by Odonno**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #1678 

## What is the new behavior?

Add `extras` property from `NavigationExtras` in every `ROUTER_REQUEST` action.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by brandonroberts** [comment]
If we include the `NavigationExtras` as is with the `ActivatedRoute`, this is going to introduce additional state which has bitten us in the past, which is also why we have serialize the `RouterStateSnapshot` . What's the advantage over combining it where needed?

**Comment by Odonno** [comment]
I don't fully understand what you said. If there is another way to use `NavigationExtras`, I would like to hear about it. Can you show me an example of what you describe?

**Comment by brandonroberts** [comment]
An example is what we what we do in router-store with the default serializer here https://github.com/ngrx/platform/blob/master/modules/router-store/src/serializer.ts. We have to strip out the mutable parts of the router state

**Comment by Odonno** [comment]
I am still not confident with this code but from what I see, you suggest we create an `ActionSerializer` the same way you created a `RouterSerializer`?

**Comment by Odonno** [comment]
Hi @brandonroberts 

I don't see where you want me to go. I only changed the `RouterRequestAction` and I don't have to update the `RouterState` at the moment.

This way, I can accomplish what I exposed in the issue #1678

**Comment by wesleygrimes** [comment]
@brandonroberts correct me if I am wrong, but what you're saying is that @Odonno can create a new custom `RouterStateSerializer` that includes the `replaceUrl`. 

@Odonno This could live in your individual projects.

**Comment by wesleygrimes** [comment]
@Odonno Are we OK to close this PR? Were you able to create a new custom `RouterStateSerializer`?

**Comment by Odonno** [comment]
@wesleygrimes Sorry for the delay. I will close this PR.

Unfortunately, I did not find a way to do what I need which is having a list of all previous pages in browser history based on angular routing and ngrx/router-store.

**Comment by wesleygrimes** [comment]
@odonno send me an email or twitter dm and I’ll see if I can help you out or get someone else to help. We want to make sure your needs are met.

**Pull request closed without merging**
