### PR TITLE
example-app: Update actions types to use enum instead of const

### PR DESCRIPTION
**Pull request by BeastCode**
Suggestion, update actions types to use enum instead of const in example-app. See Issue #597 .

I've only updated two files as an example, but can update the rest if approved. Let me know what you think.

### CODE REVIEW

**Comment by brandonroberts** [comment]
@BeastCode seems reasonable

**Comment by sharikovvladislav** [comment]
Notice https://github.com/ngrx/platform/issues/597#issuecomment-347787793.

It was changed in that commit: https://github.com/ngrx/example-app/commit/d7547f282cd3f22a1ec9e03f07e27365d5242bdb#diff-e5d3a5a3504ff9ea5eaaf397b67fbd90

**Comment by BeastCode** [comment]
@sharikovvladislav One difference between the old commit and my pr is that I’m using String Enums, which became available in TS2.4: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html

**Comment by brandonroberts** [comment]
@BeastCode are you still going to work on this PR or can this be closed?

**Comment by BeastCode** [comment]
Been away from the computer (vacation), PR is coming soon.

**Comment by brandonroberts** [comment]
:+1:

**Comment by BeastCode** [comment]
Updated PR with the rest of the files. Ready for review.

**Comment by brandonroberts** [comment]
Thanks!

**Pull request merged**
