### PR TITLE
refactor(example): enable treeshakable providers

### LINKED ISSUE #1126: Example: Convert guards/services to implement Treeshakable providers
## Other information:
If the service is eagerly loaded at the root, use the `providedIn` syntax and remove the `forRoot` implementation as needed.

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by kouMatsumoto**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1126

## What is the new behavior?
- Refactor all services and guards with treeshakable providers.
- Remove unnecessary `forRoot` methods from CoreModule and AuthModule.

## Does this PR introduce a breaking change?
This change affects only to example-app.

```
[ ] Yes
[x] No
```

## Other information
Closes #1126

### CODE REVIEW

**Comment by kouMatsumoto** [comment]
https://github.com/ngrx/platform/pull/1257/files#diff-befaf426d246fb0574c8034b64381d79R17

```
@Injectable({
  providedIn: 'root',
})
export class BookExistsGuard implements CanActivate {
```

In the new behavior `BookExistsGuard` is provided from the root injector, but in the current behavior it is provided from the injector of BooksModule.
The reason is to resolve warning of circular dependency.

```
WARNING in Circular dependency detected:
example-app/app/books/books-routing.module.ts -> example-app/app/books/guards/book-exists.guard.ts -> example-app/app/books/books.module.ts -> example-app/app/books/books-routing.module.ts

WARNING in Circular dependency detected:
example-app/app/books/books.module.ts -> example-app/app/books/books-routing.module.ts -> example-app/app/books/guards/book-exists.guard.ts -> example-app/app/books/books.module.ts

WARNING in Circular dependency detected:
example-app/app/books/guards/book-exists.guard.ts -> example-app/app/books/books.module.ts -> example-app/app/books/books-routing.module.ts -> example-app/app/books/guards/book-exists.guard.ts
```

I think guard should be provided from the room injector but l will use `providers` of @NgModule if it's preffer.
Please tell me which is good, thanks :smiley:

**Comment by kouMatsumoto** [comment]
I confirmed the application is working correctly with `yarn run example:start:aot`

**Comment by timdeschryver** [comment]
You don't need to say sorry @kouMatsumoto, we're very happy that you take the time to contribute!
Also that's what reviews are for 😄

**Comment by kouMatsumoto** [comment]
@timdeschryver 
Thank you 😄

**Pull request merged**
