### PR TITLE
Create effect migration

### PR DESCRIPTION
**Pull request by timdeschryver**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## What is the new behavior?

This PR adds a `migrateToCreators` (`mc`) flag to the effect schematics to offer a way to migrate to `createEffect`. For example

```ts
@Injectable()
export class SomeEffectsClass {
  constructor(private actions$: Actions) {}
    @Effect()
    foo$ = this.actions$.pipe(
      ofType<LoginAction | LogoutAction>('LOGIN', 'LOGOUT'),
      tap(action => console.log(action))
    );
}
```   

Would become

```ts
@Injectable()
export class SomeEffectsClass {
  constructor(private actions$: Actions) {}
  foo$ = createEffect(() => this.actions$.pipe(
    ofType<LoginAction | LogoutAction>('LOGIN', 'LOGOUT'),
    tap(action => console.log(action))
   ));
}      
```

Commit f1f95ae refactors existing schematics to use the `replaceImport` function to replace imports. 

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

I'm not sure if this is the right location to offer this migration but I couldn't find another place to introduce this schematic.

### CODE REVIEW

**Comment by dummdidumm** [comment]
Does it make sense to wait on this PR until I migrate, or is such a migration no longer planned to be part of the schematics?

**Comment by brandonroberts** [comment]
Its still planned, we just need to discuss where to put it. It isn't something you'll do often, but its not something we wanted to force into the migration to version 8. After talking to the CLI team, my thought is that it should be its own schematic instead of an option on the `effect` schematic. `ng g create-effect-migration` or something like that.

**Comment by brandonroberts** [comment]
@timdeschryver do you want to close this and open a new PR, or update the conflicts?

**Comment by brandonroberts** [comment]
Yea, a schematic would be correct. I think `ng g create-effect-migration` would be fine.

**Comment by timdeschryver** [comment]
Closing in favor of #2136

**Pull request closed without merging**
