### PR TITLE
build: fix version stamping and bump to 7.x beta.0

### PR DESCRIPTION
**Pull request by brandonroberts**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by SerkanSipahi** [comment]
@brandonroberts would you like to deploy `7.0.0-beta.0` on NPM, thanks :)

**Comment by brandonroberts** [comment]
@SerkanSipahi its published. I didn't want to deploy on Friday and/or over the weekend :-)

**Comment by SerkanSipahi** [comment]
@brandonroberts yes, you are absolutely right! Bad weekends :)

**Comment by SerkanSipahi** [comment]
@brandonroberts thanks, update done! works like a charm :)

**Comment by brandonroberts** [comment]
Great!

**Pull request merged**
