### PR TITLE
docs: fixed usage of selector with .select()

### PR DESCRIPTION
**Pull request by luchsamapparat**
## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by luchsamapparat** [comment]
My change would be equivalent to `select(state => selectValues(state)),`, but what's currently in the docs (`select(selectValues(state)),`) is just wrong. Where would the `state` variable even come from?

Please have another look.

**Comment by brandonroberts** [comment]
@luchsamapparat state is mapped to the selector for you. See

https://github.com/ngrx/platform/blob/master/modules/store/src/store.ts#L199

with usage

https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/books/containers/collection-page.component.ts.

**Comment by luchsamapparat** [comment]
The example you posted does not pass `state` to the selector:

`store.pipe(select(fromBooks.getBookCollection));`

If it were equivalent to what I'm trying to fix here, it would be

`store.pipe(select(fromBooks.getBookCollection(state)));`

Your example proves my point that it's wrong what's in the docs

**Comment by brandonroberts** [comment]
Thanks!

**Pull request merged**
