### PR TITLE
fix(schematics): add support for eslint.cjs files

### LINKED ISSUE #3583: ng schematic does not recognise .eslintrc.cjs files
### Which @ngrx/* package(s) are the source of the bug?

eslint-plugin

### Minimal reproduction of the bug/regression with instructions

1. have any project
2. with a `.eslintrc.cjs` file (see: https://eslint.org/docs/latest/user-guide/configuring/configuration-files)
3. try to install ngrx-eslint-plugin using schematics (https://ngrx.io/guide/eslint-plugin/install)
4. boom!

Screenshot 2022-09-20 at 15 37 58

### Minimal reproduction of the bug/regression with instructions

installation via schematic finds eslint config file and proceeds.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

latest angular
latest ngrx-eslint-plugin
latest eslint
latest anything

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by JeromeWirth**
Closes ngrx#3583

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [] Tests for the changes have been added (for bug fixes / features)
- [] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #3583

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by timdeschryver — CHANGES_REQUESTED** [review]
Could you add a test case for this please?
This change detects `js` config files, but I assume that the implementation (https://github.com/ngrx/platform/blob/main/modules/eslint-plugin/schematics/ng-add/index.ts#L22) needs to be updated as well.

**Comment by NathanLaing** [comment]
If this stays stale I'm happy to pick it up and write some tests.

Out of interest are other `.eslint.?` supported?
The default is `.json` so it makes sense we handle that.
The piece I am missing is is there somewhere we handle the others (i.e. `.js, .ts, .mjs`) or are they not yet supported?

**Comment by JeromeWirth** [comment]
Sorry for the late reply. This is the point where im currently stuck. For now only .json is allowed and i'm not sure how to transform it into a valid .cjs file.

Sine im bit busy currently feel free to pick it up.

**Comment by timdeschryver** [comment]
We're currently only support the `.json` format (and we have tests for this).
Because this PR is/will become stale I'm closing this.
Feel free to create a new PR with the needed changes to support other formats, e.g. `.js`.

**Pull request closed without merging**
