### PR TITLE
refactor(data): rename NgRxDataModule to EntityDataModule

### LINKED ISSUE #1777: Data: rename NgRxDataModule to EntityDataModule
To stay consistent across our modules we have to rename the following:

`NgrxDataModule`
`NgrxDataModuleWithoutEffects`
`NgrxDataModuleConfig`

### PR DESCRIPTION
**Pull request by jtcrowson**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #1777

## What is the new behavior?

To stay consistent across modules, the following was renamed:

`NgrxDataModule` -> `EntityDataModule`
`NgrxDataModuleWithoutEffects` -> `EntityDataModuleWithoutEffects`
`NgrxDataModuleConfig` -> `EntityDataModuleConfig`

## Does this PR introduce a breaking change?

```
[x] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by jtcrowson** [comment]
@timdeschryver renamed in b03eb87.

**Comment by brandonroberts** [comment]
#1767 is merged now, so you'll need to rebase on master and update the overview page also.

**Comment by jtcrowson** [comment]
@brandonroberts rebased. Updated data overview page in 7500dc0.

**Comment by brandonroberts** [comment]
We still want to refer to it as NgRx Data, with EntityData for usage

**Pull request merged**
