### PR TITLE
test(component): update usage of TestBed.get to TestBed.inject

### LINKED ISSUE #2240: Platform: Update usage of TestBed.get to TestBed.inject
`TestBed.inject` replaces `TestBed.get<Type>`. We need to clean up:

- [ ] Library code
- [ ] Docs
- [ ] Schematics

Blocked by #2234

### PR DESCRIPTION
**Pull request by sumitparakh**
angular 9 compatibillity changes for TestBed

Closes #2240

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] Testing compatibility changes for angular 9
```

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by sumitparakh** [comment]
Not sure why ci is failing.

**Comment by sumitparakh** [comment]
@timdeschryver can you review it.?

**Comment by timdeschryver** [comment]
Yes, I'm currently a bit busy but I'll get to it in a couple of days.

You can take a look at the build to see the errors, if you scroll to the bottom of the command output:

- https://circleci.com/gh/ngrx/platform/20647?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
- https://circleci.com/gh/ngrx/platform/20648?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
- https://circleci.com/gh/ngrx/platform/20651?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by brandonroberts** [comment]
Thanks for the PR @sumitparakh! 

None of the files in the `/docs` folder should be modified. They are deprecated and out of date.

**Comment by brandonroberts** [comment]
And the tests under `projects/ngrx.io/src` should not be modified either. Just the files under `projects/ngrx.io/content`

**Comment by brandonroberts** [comment]
There are still lots of files changed that shouldn't be. Please revert those changes completely, so only the actual files that need to be touched are changed.

**Comment by sumitparakh** [comment]
> There are still lots of files changed that shouldn't be. Please revert those changes completely, so only the actual files that need to be touched are changed.

@brandonroberts  Done!

**Comment by brandonroberts** [comment]
Thanks @sumitparakh!

**Pull request merged**
