### PR TITLE
docs: update NgRx logo

### PR DESCRIPTION
**Pull request by alex-okrushko**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by timdeschryver — COMMENTED** [review]
Looks good to me 🤩
Only the icon in the top-menu is a bit off

image

**Comment by alex-okrushko** [comment]
@timdeschryver how about all white?
Screenshot 2024-01-29 at 1 31 06 PM

**Review by timdeschryver — APPROVED** [review]
LGTM!

**Review by brandonroberts — APPROVED** [review]

**Review by markostanimirovic — APPROVED** [review]
🚀

**Pull request merged**
