### PR TITLE
docs: update generated example dependencies to Angular v8-beta and NgRx v7.4

### LINKED ISSUE #1703: Docs: update example dependencies to version 8
The dependencies for the generated examples need to be updated with the upcoming release. The `package.json` file is located in the `projects/ngrx.io/tools/examples/shared` folder. 

- [ ] Update the Angular dependencies to latest 
- [ ] Update the NgRx dependences to latest
- [ ] Run yarn in the `shared` folder to update the `yarn.lock` file

### PR DESCRIPTION
**Pull request by jtcrowson**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #1703

## What is the new behavior?

Updated dependencies for the generated examples with the upcoming release.
- Updated Angular dependencies to latest v8-beta
- Updated NgRx dependences to latest v7.4.0
- Updated `yarn.lock` file

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by jtcrowson** [comment]
Are generated docs being used in ngrx.io currently?

**Comment by brandonroberts** [comment]
The generated store example is at `/generated/live-examples/store/stackblitz.html`

**Comment by brandonroberts** [comment]
Will you update this file also https://github.com/ngrx/platform/blob/master/projects/ngrx.io/tools/examples/shared/boilerplate/cli/package.json

**Comment by jtcrowson** [comment]
Sure thing! `projects/ngrx.io/tools/examples/shared/boilerplate/cli/package.json` updated in 53b4c47.

**Comment by brandonroberts** [comment]
Remove the new `cli/yarn.lock` file. Everything else LGTM

**Comment by jtcrowson** [comment]
@brandonroberts removed in 6e9952f.

**Pull request merged**
