### PR TITLE
feat(store): make toActionName case more customizable

### LINKED ISSUE #3693: Allows createActionGroup to preserve the case
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

I would like to be able to preserve the case of the event keys I put :grimacing: 

image

By the way: thank you very much for the improved APIs, I am totally fan! 

### Describe any alternatives/workarounds you're currently using

image

Unfortunately it will considerably increase any refactoring effort, I really like to have the name of my action being the name of its variable + (removing the spaces for the name of actions allows to have more characters visible in the Redux DevTools which helps a lot in case of long names).

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by hadrien-toma**
## PR Checklist

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Closes #3693

## What is the new behavior?

image

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by markostanimirovic** [comment]
Hi @hadrien-toma 👋 

Thanks for opening this PR! However, it would introduce a **breaking change**, so it won't be possible to include this change in a minor v15 release.

I'm going to close this PR for now. We'll consider request #3693 for the next major release.

**Comment by hadrien-toma** [comment]
Alright, thank you for your answer. May you help me to understand where the breaking change is? I thought it was retrocompatible beauce I thought it was only enlarging the type 😬.

By the way: the v15 is simply amazing, thank you very much 👌🚀! Can't wait to use actionGroup now 😋

**Comment by hadrien-toma** [comment]
Also @markostanimirovic I propose to give help by adding a unit test highlighting this breaking change when I have understood it if you think it could be interesting 😊

**Comment by markostanimirovic** [comment]
Thank you! 😊

> May you help me to understand where the breaking change is?

If we introduce this change, the following code that is currently correct will not compile:

```ts
const UsersApiActions = createActionGroup({
  source: 'Users API',
  events: {
    'USERS Loaded Success': emptyProps(),
  },
});

// compilation of the line below succeeds with the current NgRx version
UsersApiActions.usersLoadedSuccess();
// however, if we introduce the change from this PR, compilation will fail
// because the action name will be `uSERSLoadedSuccess`
```

These tests validate the current behavior:
- https://github.com/ngrx/platform/pull/3695/files#diff-ea3185170f36adfef9dccbf98bd0b7ab350c483f7807c9691ad50023abf6bb5fL21
- https://github.com/ngrx/platform/pull/3695/files#diff-3384d5be8438d0ef687ffdd0f10b89acaf32209033f91f72a1f1d2331363d1efL83

**Comment by hadrien-toma** [comment]
Ah! Thank you very much @markostanimirovic ! I think I understand better now! So... I dare to ask :sweat_smile: : would it be okay if I suggest a PR with another function named toActionNameCaseSensitive and add the rest of the code to independently support this new functionality by only "adding" codes (and their tests)? It would be so nice if I could group my actions even in v15 :scream: :sweat_smile:. Also I am currently rewritting my Nx generators so it would be very nice if I can have the maximum of new feature in them before the technical debt is spread everywhere :grimacing:

**Comment by timdeschryver** [comment]
We won't extend our current API with `toActionNameCaseSensitive`. Doing this adds another surface that needs to be maintained, and could be removed in v16 (if we change the current behavior) resulting in a breaking change.
If it's really blocking I would suggest you to create `toActionNameCaseSensitive` in your codebase, which could be replaced with our API in the future.

I do think it make sense to keep the casing.
e.g.

```ts
'USERS Loaded Success' => USERSLoadedSuccess
'USERS loaded success' => USERSLoadedSuccess
'Users loaded success' => UsersLoadedSuccess
UsersLoadedSuccess => UsersLoadedSuccess
```

**Comment by hadrien-toma** [comment]
Thank you for your answer @timdeschryver, this is noted and I appreciate you still consider to conserve the case as you presented in the future
 I will create the wrapper on my side for the moment, thanks for the tip. I am also available to help on any PR/changes you think is relevant regarding this behavior 😊.

I take the opportunity to detail a little bit more my usage : on my case I don't like to have to maintain the type of an action + its variable name. All my actions' names are equal to their type which reduces the number of name/case to find, ensure and maintain (it is especially useful when refactoring). Because of that I never have spaces in my actions' names so the casing transformation you suggested would be completely fine on my side 🙂.

**Comment by TJMaria** [comment]
I agree with @hadrien-toma. As a developer i find it more important to easily be able to:
- find usages of an action (dispatch, reducer, effect) --> event/action key is the same everywhere
- easily refactor an actionName

A developer/team should be able to determine the casing used.
Only the actionType is 'negatively' affected, but honestly even there i prefer the type name without spaces.

I created a PR with a different approach (before i read these comments): https://github.com/ngrx/platform/pull/3736

As stated in the comment of my PR:

> Prefered would be to make it configurable, but the current ActionGroup type contains the ActionName type that influence the casing.

**Comment by TJMaria** [comment]
For now i'm using a static class with utility functions as an alternative to createActionGroup
see https://github.com/ngrx/platform/pull/3736#issuecomment-1369785798

**Pull request closed without merging**
