### PR TITLE
feat(data): Introduce Standalone API for NgRx Data

### LINKED ISSUE #3529: Data: Introduce Standalone API for NgRx Data
### Information

Introduce standalone APIs for using the `@ngrx/data` package. This should allow developers to use NgRx Data in a "module-free" application.

Based on the discussion in #3399

```ts
provideEntityData(config)
```

This function will make use of the [ENVIRONMENT_INITIALIZER](https://angular.io/api/core/ENVIRONMENT_INITIALIZER) token to perform any init logic that was previously done in the NgModule constructor.

### Describe any alternatives/workarounds you're currently using

Using `importProvidersFrom` function:

```ts
// main.ts
bootstrapApplication(AppComponent, {
  providers: [importProvidersFrom(EntityDataModule.forRoot(entityConfig))]
});
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by santoshyadavdev**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #3529

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by markostanimirovic — CHANGES_REQUESTED** [review]

**Comment by santoshyadavdev** [comment]
Hi Team, I need help with type error 

modules/data/src/provide_entity_data.ts:80:7 - error TS7018: Object literal's property 'useValue' implicitly has an 'any[] | EntityMetadataMap' type.

 useValue: config.entityMetadata ? config.entityMetadata : [],

@timdeschryver @markostanimirovic

**Comment by markostanimirovic** [comment]
Hey @santoshyadavdev,

Build error (issue with `noImplicitAny`) can be fixed by adding a return type to the `_provideEntityData` function:

```diff
-export function _provideEntityData(config: EntityDataModuleConfig) {
+export function _provideEntityData(config: EntityDataModuleConfig): Provider[] {
```

**Comment by brandonroberts** [comment]
@santoshyadavdev let us know if you need any more assistance on this. We'd like to land it for v15

**Comment by santoshyadavdev** [comment]
I think I need to fix tests, will check today, And let you know if I need any help.

**Comment by santoshyadavdev** [comment]
Hi team can I get some help on this test failure

The error is : No provider for InjectionToken @ngrx/data Entity Cache Selector!

**Comment by santoshyadavdev** [comment]
Cc @brandonroberts @markostanimirovic

**Comment by markostanimirovic** [comment]
Hey @santoshyadavdev,

Sorry, I accidentally pushed changes from the master to your branch 😅, and now I don't have permission to push the fix, because the PR was automatically closed.

Can you please re-open the PR? Here are the changes that should fix it: https://github.com/ngrx/platform/commit/8f805ef8b55212c3073676a0e3cb2e3d9e6d9880

**Pull request closed without merging**
