### PR TITLE
feat(schematics): add component store schematics

### LINKED ISSUE #2570: Schematics: add schematic for component store
Add a new schematic to generate:

A service that extends ComponentStore
A spec file if requested
Maybe an inlined interface for the default type

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by stefanoww**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #2570

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by brandonroberts** [comment]
You need to run `yarn copy:schematics` to copy the schematics-core into the other libraries. That should fix the CI error

**Comment by va-stefanek** [comment]
> You need to run `yarn copy:schematics` to copy the schematics-core into the other libraries. That should fix the CI error

It cause newly added methods disappearing from the ast-utils.ts. Is that expected?

**Comment by brandonroberts** [comment]
Yes. You need to add the changes to modules/schematics-core first, then run the command to sync the changes in all the libraries. We do it this way because it's not currently a standalone package

**Comment by va-stefanek** [comment]
@brandonroberts seems to be fine now despite of Labeler which probably fail for the forks.

**Comment by brandonroberts** [comment]
One request would be to change the test scaffolding to not use the TestBed, and just create a new instance of the ComponentStore

cc: @alex-okrushko

**Comment by stefanoww** [comment]
@brandonroberts done.

**Comment by fgoulet** [comment]
While waiting for the PR to be reviewed, is there a sample of a spec file generated with this schematic somewhere ? I'm looking for something to help me with unit testing in component store.

**Comment by brandonroberts** [comment]
The spec is pretty minimal. The <% references are just placeholders

```ts
import { <%= classify(name) %>Store } from './<%= dasherize(name) %>.store';

describe('<%= classify(name) %>Store', () => {
  const componentStore = new <%= classify(name) %>Store();

  it('should be created', () => {
    expect(componentStore).toBeTruthy();
  });
});
```

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
