### PR TITLE
docs: update footer year to 2022

### LINKED ISSUE #3288: ngrx.io: update footer year to 2022 🎄
Update year in [footer.component.html](https://github.com/ngrx/platform/blob/master/projects/ngrx.io/src/app/layout/footer/footer.component.html#L20) file to 2022.

### PR DESCRIPTION
**Pull request by Ankita-singh-05**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #3288 

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by timdeschryver — APPROVED** [review]
Looks good to me.
@Ankita-singh-05 a nit for the next time.
It's useful if you could add the issue number in the PR description (see the template).

E.g. 

Closes #3289

**Review by markostanimirovic — APPROVED** [review]

**Comment by markostanimirovic** [comment]
Thanks @Ankita-singh-05!

**Comment by Ankita-singh-05** [comment]
> Looks good to me. @Ankita-singh-05 a nit for the next time. It's useful if you could add the issue number in the PR description (see the template). For example:
> 
> Closes #3288

Thank you so much, Sir! I will do it next time.

**Comment by Ankita-singh-05** [comment]
> Thanks @Ankita-singh-05!

My pleasure! 😊

**Pull request merged**
