### PR TITLE
renamed files to be consistent with cli, closes #983

### LINKED ISSUE #983: Inconsistent naming
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is the current behavior?
I'm attempting to map out a step-by-step procedure for generating the example app and I've noticed there are a few filenames that are inconsistent:

```
login-form.component.ts
login-form.component.spec.ts
login-page.component.ts
login-page.component.spec.ts
auth.effects.ts
auth.effects.spec.ts
auth-guard.service.ts
auth-guard.service.spec.ts
auth.service.ts
```

## Expected behavior:
Everything else doesn't have the `.component|.effects|.service` parts of the names.

I also haven't found an easy way with angular-cli to rename files, I've been having to use a rename script to regex remove all of these names.  It would make it easier to reproduce if everything had their original file types in the names.

## Other information:
This isn't a huge deal, but I'm planning on writing up the step-by-step instructions to recreate the example app anyways, so maybe I can submit a PR for the instructions as part of the README and fix the file names while I'm at it?

### PR DESCRIPTION
**Pull request by martzcodes**
Files are renamed to be consistent with how the angular-cli and ngrx-schematics name the files on creation.

I validated by running `npm run example:test`, `npm run example:build:prod` and `npm run example:start`

Closes #983

### CODE REVIEW

**Comment by brandonroberts** [comment]
Undo the change to the `tools/bazel_stamp_vars.sh` file

**Comment by martzcodes** [comment]
@brandonroberts Hmm... I'm not showing any changes in that file, just pasted from master and there's nothing to commit

**Comment by martzcodes** [comment]
@brandonroberts I think it had to do with removing the cached files and re-adding the script file... so I went back and added the gitignore change to the first commit so i didn't have to remove cached.

**Comment by brandonroberts** [comment]
Thanks!

**Pull request merged**
