### PR TITLE
docs: add signals package to the list of supported scopes

### PR DESCRIPTION
**Pull request by rainerhahnekamp**
- add signals as new scope
- sort scope list alphabetically

**IMPORTANT: I didn't add schematics-core. Please let me know if I should update my PR**

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?

CONTRIBUTING.md reflects the current scopes.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by markostanimirovic — APPROVED** [review]
LGTM 👍 

We should also update the list of packages in the issue templates: https://github.com/ngrx/platform/tree/main/.github/ISSUE_TEMPLATE

**Comment by rainerhahnekamp** [comment]
I've updated the template files. I see that you have a **labeler.yml**. It looks like it has no effect. Can I remove it as well?

**Comment by markostanimirovic** [comment]
> I've updated the template files. I see that you have a labeler.yml. It looks like it has no effect. Can I remove it as well?

Yes, it's not used (currently). Feel free to revert changes in this file.

**Review by brandonroberts — APPROVED** [review]
LGTM. Changes to the labeler.yml can be reverted.

**Comment by rainerhahnekamp** [comment]
@markostanimirovic @brandonroberts remove or revert? I'd have removed it because it is not needed.

**Comment by brandonroberts** [comment]
Removing it is fine

**Comment by rainerhahnekamp** [comment]
done

**Review by brandonroberts — APPROVED** [review]

**Comment by markostanimirovic** [comment]
Thanks Rainer!

**Pull request merged**
