### PR TITLE
feat(store): loosen createSelector typings over multiple feature stat…

### LINKED ISSUE #3707: RFC: Unable to createSelector from multiple createFeature states.
### Which @ngrx/* package(s) are relevant/related to the feature request?

store

### Information

Cannot create a selector across features because of restricted typings.
The following code:
```ts
import { createFeature, createReducer, createSelector } from '@ngrx/store';

interface Feature1FeatureState {
  feature1: Feature1State;
}
interface Feature1State {
  isLoading: boolean;
}
const feature1InitialState: Feature2State = {
  isLoading: false
};
const feature1 = createFeature<Feature1FeatureState>({
  name: 'feature1',
  reducer: createReducer(feature1InitialState)
});

interface Feature2FeatureState {
  feature2: Feature2State;
}
interface Feature2State {
  isLoading: boolean;
}
const feature2InitialState: Feature2State = {
  isLoading: false
};
const feature2 = createFeature<Feature2FeatureState>({
  name: 'feature2',
  reducer: createReducer(feature2InitialState)
});

const crossFeatureSelector = createSelector(
  feature1.selectIsLoading,
  feature2.selectIsLoading,
  (isLoading1, isLoading2) => isLoading1 && isLoading2
);
```

Will result in the following compiler error:
```
No overload matches this call.
  Overload 1 of 26, '(s1: Selector<Feature1FeatureState, boolean>, s2: Selector<Feature1FeatureState, boolean>, projector: (s1: boolean, s2: boolean) => unknown): MemoizedSelector<...>', gave the following error.
    Argument of type 'MemoizedSelector<Feature2FeatureState, boolean, DefaultProjectorFn<boolean>>' is not assignable to parameter of type 'Selector<Feature1FeatureState, boolean>'.
      Types of parameters 'state' and 'state' are incompatible.
        Property 'feature2' is missing in type 'Feature1FeatureState' but required in type 'Feature2FeatureState'.
  Argument of type '[MemoizedSelector<Feature1FeatureState, boolean, DefaultProjectorFn<boolean>>, MemoizedSelector<Feature2FeatureState, boolean, DefaultProjectorFn<...>>, (isLoading1: boolean, isLoading2: boolean) => boolean]' is not assignable to parameter of type '[...slices: Selector<Feature1FeatureState, unknown>[], projector: unknown] & [Selector<Feature1FeatureState, boolean>, Selector<Feature1FeatureState, boolean>, (s_0: boolean, s_1: boolean) => unknown]'.
    Type '[MemoizedSelector<Feature1FeatureState, boolean, DefaultProjectorFn<boolean>>, MemoizedSelector<Feature2FeatureState, boolean, DefaultProjectorFn<...>>, (isLoading1: boolean, isLoading2: boolean) => boolean]' is not assignable to type '[...slices: Selector<Feature1FeatureState, unknown>[], projector: unknown]'.
      Type at positions 0 through 1 in source is not compatible with type at position 0 in target.
        Type 'MemoizedSelector<Feature1FeatureState, boolean, DefaultProjectorFn<boolean>> | MemoizedSelector<Feature2FeatureState, boolean, DefaultProjectorFn<...>>' is not assignable to type 'Selector<Feature1FeatureState, unknown>'.
          Type 'MemoizedSelector<Feature2FeatureState, boolean, DefaultProjectorFn<boolean>>' is not assignable to type 'Selector<Feature1FeatureState, unknown>'.
            Types of parameters 'state' and 'state' are incompatible.
              Type 'Feature1FeatureState' is not assignable to type 'Feature2FeatureState'.
  Overload 3 of 26, '(s1: SelectorWithProps<Feature1FeatureState, unknown, boolean>, s2: SelectorWithProps<Feature1FeatureState, unknown, boolean>, projector: (s1: boolean, s2: boolean, props: unknown) => unknown): MemoizedSelectorWithProps<...>', gave the following error.
    Argument of type 'MemoizedSelector<Feature2FeatureState, boolean, DefaultProjectorFn<boolean>>' is not assignable to parameter of type 'SelectorWithProps<Feature1FeatureState, unknown, boolean>'.
      Types of parameters 'state' and 'state' are incompatible.
        Type 'Feature1FeatureState' is not assignable to type 'Feature2FeatureState'.ts(2769)
test.reducer.ts(18, 3): 'feature2' is declared here.
```

### Describe any alternatives/workarounds you're currently using

````ts
const workaroundCrossFeatureSelector = createSelector<Feature1FeatureState | Feature2FeatureState, boolean, boolean, boolean>(
  feature1.selectIsLoading,
  feature2.selectIsLoading,
  (isLoading1, isLoading2) => isLoading1 && isLoading2
);
````

But writing code like this can become quite tedious.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by albert-m-willemsen**
…es (#3707)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #3707 

## What is the new behavior?
Allow createSelector over multiple feature states.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by timdeschryver — COMMENTED** [review]
This should also include a type test at https://github.com/ngrx/platform/tree/master/modules/store/spec/types.

As a workaround you can also omit the generic from `createFeature`

```ts
const feature1 = createFeature({
  name: 'feature1',
  reducer: createReducer(feature1InitialState)
});
```

**Comment by albert-m-willemsen** [comment]
For tests where do I begin/put them? Selector or Feature?

**Comment by albert-m-willemsen** [comment]
Is my solution even the correct solution for this problem?

**Comment by timdeschryver** [comment]
@albert-m-willemsen this will be resolved with https://github.com/ngrx/platform/issues/3737

**Pull request closed without merging**
