### PR TITLE
fix(store-devtools): replace direct with indirect `eval`

### LINKED ISSUE #4213: warning generated when using esbuild
### Which @ngrx/* package(s) are the source of the bug?

store-devtools

### Minimal reproduction of the bug/regression with instructions

When compiling with the new esbuild system in Angular 17 (https://angular.io/guide/esbuild), the following warning is generated:
```
Using direct eval with a bundler is not recommended and may cause problems [direct-eval]

    node_modules/@ngrx/store-devtools/fesm2022/ngrx-store-devtools.mjs:423:42:
        432 | ....return typeof action === 'string' ? eval(`(${action})`) : action;
            |                                                  ~~~~

    You can read more about direct eval and bundling here: https://esbuild.github.io/link/direct-eval
```

### Expected behavior

No warnings should be generated.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 17.0.1
Angular: 17.0.8

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by rainerhahnekamp**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

From my perspective, this removes the unnecessary `eval` method to get an action's payload.

If somebody knows why the `eval` was there in the first place (no test is failing), we could provide a safer, alternative version of `unwrapAction`.

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #4213

## What is the new behavior?

The `payload` is directly used.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by timdeschryver — COMMENTED** [review]
The `eval` is probably there because you can dispatch an action via the DevTools. I assume this is just a string, and `eval` parses it to an action object.

IIRC manually dispatching actions didn't completely work with the NgRx global store. 
I'll test/verify this later this week, if that's the case we can also resort to the alternatives mentioned in https://esbuild.github.io/content-types/#direct-eval

**Comment by rainerhahnekamp** [comment]
Got it, will do and also add a unit tests so that in the future it is clear why we require that kind of feature.

**Comment by rainerhahnekamp** [comment]
Okay, @timdeschryver, the updated version with tests has been pushed.

**Review by timdeschryver — APPROVED** [review]
Thanks @rainerhahnekamp !

**Comment by markostanimirovic** [comment]
@rainerhahnekamp is the PR title still relevant? I guess we should update it since `eval` and `unwrapAction` are still there.

**Comment by rainerhahnekamp** [comment]
@markostanimirovic, you're right. I've renamed the title.

**Review by markostanimirovic — APPROVED** [review]
Thanks Rainer!

**Pull request merged**
