### PR TITLE
chore(docs): remove `--` from yarn run

### PR DESCRIPTION
**Pull request by phra**
the `--` to escape arguments is not needed anymore. ref -> https://yarnpkg.com/lang/en/docs/cli/run/#toc-yarn-run-script

### CODE REVIEW

**Comment by brandonroberts** [comment]
This is for the latest version of yarn, so the minimum version in the `engines` section of the `package.json` needs to be updated also along with the scripts.

**Comment by phra** [comment]
@brandonroberts it will be deprecated, so it's breaking anyway in the end.

**Comment by brandonroberts** [comment]
@phra yes, but only changing the instructions is going to lead to an error unless you have the latest version. To prevent that, the requirements need to be updated so we have a baseline.

**Comment by phra** [comment]
@brandonroberts this is not valid just for the latest version of yarn.. the deprecation message states:

```
yarn run v1.3.2
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
```

btw i've updated the mininum version required for yarn from 1.1.0 -> 1.3.2 and removed the deprecation warning from the circleci build.

**Comment by brandonroberts** [comment]
@phra thanks! Will you update the scripts in the `package.json` that have the dashes? Then this will be ready to land

**Comment by phra** [comment]
done!

**Comment by brandonroberts** [comment]
Thanks!

**Pull request merged**
