### PR TITLE
docs(data): selectors

### LINKED ISSUE #2124: @ngrx/data : documenting selectors
###  Other information:
My Scenario:  
  
Existing large codebase with multiple entities  

Currently combining multiple pieces of state with selectors like:
```ts
export const selectedCatsWithOwners = createSelector(
  selectAllCats,
  selectOwnersEntities,
  (cats, ownerEntities) => cats.map(c => ({
    ...c,
    owner: ownerEntities[c.owner]
  }))
);
```

I'd like to use @ngrx/data with Owners and keep everything else the same.  That means replacing the existing `selectOwnersEntities` selector (provided by @ngrx/entity) with similar from @ngrx/data.

So I found the elegant solution provided by @ngrx/data:

```ts
export const ownerSelectors = new EntitySelectorsFactory().create<Owner>('Owner');

export const selectedCatsWithOwners = createSelector(
  selectAllCats,
  ownerSelectors.selectEntities,
  (cats, ownerEntities) => cats.map(c => ({
    ...c,
    owner: ownerEntities[c.owner]
  }))
);
```

That said, `new EntitySelectorsFactory().create<Owner>('Owner');` is not documented anywhere. And I think it should be.

## I would be willing to submit a PR for the docs :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by peterbsmith2**
Closes #2124

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Undocumented [EntitySelectorsFactory](https://ngrx.io/api/data/EntitySelectorsFactory)

Closes #

## What is the new behavior?

Documents an example of using [EntitySelectorsFactory](https://ngrx.io/api/data/EntitySelectorsFactory)

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

This is a first pass, is it ok to have it in the advanced section or do you prefer it somewhere else?

### CODE REVIEW

**Comment by peterbsmith2** [comment]
@timdeschryver I could see this living in Extensions Points as "Custom Selectors"

**Comment by timdeschryver** [comment]
Sounds good to me @peterbsmith2

**Comment by peterbsmith2** [comment]
@timdeschryver i updated the docs to have a 'custom selectors' section in Extension Points

**Comment by brandonroberts** [comment]
The preview isn't display correctly. I think there needs to be some line breaks in between the headers and content

**Comment by peterbsmith2** [comment]
@brandonroberts I looked at the preview and i updated some spacing and i looked at the preview again. and it appears to be broken now the same as before. any other suggestions?

**Comment by brandonroberts** [comment]
@peterbsmith2 yep, wrap the `@ngrx/*`references in backticks. The markdown parser doesn't like lines to begin with `@` for some reason I'm unaware of.

**Comment by peterbsmith2** [comment]
@brandonroberts it looks like backticks did the trick, preview is viewable.

**Pull request merged**
