### PR TITLE
refactor(schematics): toggle immutability checks for root by default

### LINKED ISSUE #1950: RFC: schematics should toggle immutability checks on by default
When using the schematics to create a `root` store, I think it would be a good practice to turn the immutability checks on.

```ts
runtimeChecks: {
        strictStateImmutability: true,
        strictActionImmutability: true,
},
```

And what about the serializability checks?

## Describe any alternatives/workarounds you're currently using

Now the user needs to add it manually.

### PR DESCRIPTION
**Pull request by itayod**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?

when use schematics `forRoot` toggle runtime checks by default.

Closes #1950

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by itayod** [comment]
@timdeschryver 
Currently added: 
`strictStateImmutability: true`,
`strictActionImmutability: true`

What do you think about adding the `strictStateSerializability` & ` strictActionSerializability`?

**Comment by brandonroberts** [comment]
I don't think we need another flag for this. It's a reasonable default and is easy enough to remove.

**Comment by itayod** [comment]
> I think immutability is important, serializability isn't always needed and might backfire if you aren't careful. For now, I would leave it as it is.
> 
> Do you also want to add the schematic in the docs at https://ngrx.io/guide/schematics/store?
> Feel free to ping me if you need some help.

Sure, I will update the docs thanks :) 👍

**Comment by itayod** [comment]
@brandonroberts I have removed the flag as you suggested

**Comment by itayod** [comment]
> > I think immutability is important, serializability isn't always needed and might backfire if you aren't careful. For now, I would leave it as it is.
> > Do you also want to add the schematic in the docs at https://ngrx.io/guide/schematics/store?
> > Feel free to ping me if you need some help.
> 
> Sure, I will update the docs thanks :) 👍

@timdeschryver after removing the flag there is no need to update the docs

**Pull request merged**
