### PR TITLE
build(example): update angular deeps to v 10 rc

### LINKED ISSUE #2560: Docs: update example dependencies to latest Angular version 10 release
The dependencies for the generated examples need to be updated with the upcoming release. The `package.json` file is located in the `projects/ngrx.io/tools/examples/shared` folder. 

- [ ] Update the Angular dependencies to latest 
- [ ] Update the NgRx dependences to latest
- [ ] Run yarn in the `shared` folder to update the `yarn.lock` file

### PR DESCRIPTION
**Pull request by jordanpowell88**
Closes #2560

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #2560 

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by timdeschryver** [comment]
Seems like we'll have to update the [node version of the image we use for the docs](https://github.com/ngrx/platform/blob/master/.circleci/config.yml#L26)

```
[3/5] Fetching packages...
error move-file@2.0.0: The engine "node" is incompatible with this module. Expected version ">=10.17". Got "10.16.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
/home/circleci/docs/projects/ngrx.io/node_modules/yargs/yargs.js:1078
      else throw err
```

**Comment by jordanpowell88** [comment]
@timdeschryver do you want me to do that? Where is that set?

**Comment by timdeschryver** [comment]
I think you can upgrade it to `circleci/node:12.9.1`. 
It's set in the circle ci config, linked my comment.

**Comment by jordanpowell88** [comment]
Sorry Tim, I didn't see your original link. Should be good to go now

**Pull request merged**
