### PR TITLE
feat(router-store): add action types

### LINKED ISSUE #44: [router-store] Missing Actions classes
You should create Actions classes for `router-store` to avoid this kind of reducer definitions :
```
export function reducer(
  state: State = initialState,
  action: feature.Actions | { type: string, payload?: any },
  ) : State {
  switch (action.type) {
    case fromRouter.ROUTER_NAVIGATION: {
    }
    case feature.MY_FEATURE_ACTION: {
    }
}
```
(or bring back the Action interface with the payload property)

### PR DESCRIPTION
**Pull request by vsavkin**
Closes #44

### CODE REVIEW

**Comment by bbaia** [comment]
A global Actions type is missing:
```
export type RouterActions 
  = RouterNavigationAction
  | RouterCancelAction
  | RouterErrorAction;
```
to allow this:
```
export function reducer(
  state: State = initialState,
  action: fromFeature.Actions | fromRouter.RouterActions,
  ) : State {
  switch (action.type) {
    case fromRouter.ROUTER_NAVIGATION: {
    }
    case fromFeature.MY_FEATURE_ACTION: {
    }
}
```

**Comment by vsavkin** [comment]
See here https://github.com/ngrx/platform/pull/47/files#diff-27504ab9d5335c0099554673e58e5eb1R74

**Comment by bbaia** [comment]
Oups, missed it, sorry.
Why don't you extended existing interface `Action` from ngrx/store ?

**Comment by vsavkin** [comment]
@bbaia no reason. Just updated the PR to extend Action.

**Pull request merged**
