### PR TITLE
docs(data): add api response explanations

### LINKED ISSUE #1939: Docs: Explain what should the DataService server respond for ngrx/data to work properly
The documentation is lacking how should the DataServer, responding to ngrx/data, actually respond in order for the client to work properly. You talk a little bit about DELETE returning a 404, but you don't talk about what should be returned for add(), delete(), getAll().

For instance, should add() return the whole instance added or just the ID? Looking at the code, it seems that the ID might be sufficient.

For the `getWithQuery`, you should mention how you will send the query to the server... QueryString? POST?, etc.

### PR DESCRIPTION
**Pull request by yharaskrik**
Adds return types for the DataService methods as well as an explanation of what the server should be returning for each.

resolves #1939

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #1939

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by yharaskrik** [comment]
Looks like the doc bot isn't working quite right.

**Review by timdeschryver — APPROVED** [review]
LGTM, what do you mean that the bot isn't working?

**Comment by yharaskrik** [comment]
Oh the link works now! It was 404ing for me before.

**Comment by timdeschryver** [comment]
Yea, I think it needs a while ... 😅

**Comment by yharaskrik** [comment]
All good! Glad it ended up looking right.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks @yharaskrik!

**Comment by yharaskrik** [comment]
No problem! I'll try and get some more explanations written up in the coming weeks! Working on a guide for ngrx data on dev.to right now as well.

**Pull request merged**
