### PR TITLE
docs(contributing): add commands to run specific unit tests

### PR DESCRIPTION
**Pull request by rovshenn**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?
Documentation change only for contributing

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by alex-okrushko** [comment]
Looks right.
@timdeschryver is there anything to add here?

**Review by alex-okrushko — APPROVED** [review]

**Review by timdeschryver — CHANGES_REQUESTED** [review]
Can you prefix these commands with `yarn` please? 
The reason is that not everyone has `nx` or `jest` installed globally.

```
yarn nx test effects
```

**Comment by rovshenn** [comment]
Sure @timdeschryver , will do! Good idea.

**Review by timdeschryver — APPROVED** [review]
Great, thanks @rovshenn !

**Pull request merged**
