### PR TITLE
feat(effects): limit retries to 10 by default

### LINKED ISSUE #2303: Effects: resubscribeOnError for "broken" effect results in infinite loop and ends with "RangeError: Maximum call stack size exceeded"
## Minimal reproduction of the bug/regression with instructions:

This one ended up being very hard to debug. (Resulted from the recent merge to Google attempt).

There is a test that imports a Module that imports many other Modules. Some of them import `EffectsModule.forFeature(...)`.
The author of the test tried hard to substitute all the Effects Classes with empty objects, so that effects are not running (with many `{provide: FooEffects, useValue: {}}`), however missed one. 
That one missed effect was producing an error immediately (due to the fact that it was using `store.select(selector)` and it was erroring within a `selector`)
Anyhow, the effect was immediately resubscribing and resubscribing, eventually ending up with _"RangeError: Maximum call stack size exceeded"_ error.

Nothing in the stacktrace was pointing to the resubscribing effect (and led to significant debugging time).

## Expected behavior:

Maybe after a number of failed attempts we should actually fail the effect? 100? And make it configurable. 
I wonder if that would still be better that a potentially frozen prod app.

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by alex-okrushko**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

Limit the number of retries to 10 by default

What kind of change does this PR introduce?

Removes infinite loop if the effect is producing errors on every retry

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #2303

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by brandonroberts** [comment]
The changes LGTM. Is it correct that if you want to only change the number of retries, you still have to re-implement the default behavior plus that change?

**Comment by alex-okrushko** [comment]
> Is it correct that if you want to only change the number of retries, you still have to re-implement the default behavior plus that change?

One can provide the custom effects error handler like this:
```ts
@NgModule({
  imports: [EffectsModule.forRoot([MovieEffects])],
  providers: [
    {
      provide: EFFECTS_ERROR_HANDLER,
      useValue: customEffectResubscriptionHandler,
    },
    
  ],
})

// adjust the number of retries
const CUSTOM_NUMBER_OF_RETRIES = 100; 

export function customEffectResubscriptionHandler<T extends Action>(
  observable$: Observable<T>,
  errorHandler: CustomErrorHandler
): Observable<T> {
  return defaultEffectsErrorHandler(observable$, errorHandler, CUSTOM_NUMBER_OF_RETRIES);
}
```

Thank means that there's no need to reimplement the behavior if one wants to increase the retries number.

**Comment by timdeschryver** [comment]
I find that the above snippet can be added to the docs.
If you agree, I can open up a PR for it 🙂

**Comment by alex-okrushko** [comment]
Good idea @timdeschryver

**Pull request merged**
