### PR TITLE
fix(Entity): updateOne/updateMany should not change ids state on existing entity

### LINKED ISSUE #571: updateOne/updateMany should not change ids state on existing entity
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

updateOne/updateMany updates ids state when updating existing entity.

## Expected behavior:

updateOne/updateMany should not change ids state if you attempt to update an entity that has already been added.

## Minimal reproduction of the problem with instructions:

Did not run it, but try something like that
```
  it('should not change ids state if you attempt to update an entity that has already been added', () => {
    const withOne = adapter.addOne(TheGreatGatsby, state);
    const changes = { title: 'A New Hope' };

    const withUpdates = adapter.updateOne(
      {
        id: TheGreatGatsby.id,
        changes,
      },
      withOne
    );

    expect(withOne.ids).toBe(withUpdates.ids);
  });
```

### PR DESCRIPTION
**Pull request by bbaia**
Closes #571

Needed to create a DidMutate enum, tell me what your think.
This PR only fixes the unsorted state adpater.

### CODE REVIEW

**Comment by MikeRyanDev** [comment]
This seems like a reasonable way to address the issue. Do you want to fix both adapters here or merge this one in and then fix the other in a followup PR?

**Comment by bbaia** [comment]
The sorted state adpater is a bit more complex, the same code is used for both add and update methods.
I will try to fix it and merge with this one when PR #550 will be merged.

**Comment by bbaia** [comment]
Fixed sorted state adpater, amend and rebase done.

**Comment by brandonroberts** [comment]
Thanks!

**Pull request merged**
