### PR TITLE
feat(schematics): add createEffect migration

### PR DESCRIPTION
**Pull request by timdeschryver**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## What is the new behavior?

This PR adds a new schematic `create-effect-migration` to migrate from the `@Effect()` decorator to the `createEffect()` function.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by dummdidumm** [comment]
I don't see a test for 

```ts
@Effect()
effectAsMethod() {
   return this.actions$...;
}
```

Did you check that this gets migrated, too? Or will these intentionally not get migrated?

**Comment by timdeschryver** [comment]
Thanks @dummdidumm !
I haven't thought of it, I usually see the syntax covered in the PR.

**Comment by evgenyfedorenko** [comment]
Also maybe as a part of this PR information about this migration should be added to the documentation?

**Comment by timdeschryver** [comment]
⚠ Do not merge now ⚠

There's an issue with this migration, the `createEffect` function can be imported for a second time if it's already been imported before the schematic has run.

**Comment by timdeschryver** [comment]
Removing the `WIP` tag, I verified it works now against our code base.

**Pull request merged**
