### PR TITLE
fix(Example): linter problems

### LINKED ISSUE #1592: example-app: vscode reports Typescript problems
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

image

## Expected behavior:

No problems

## Other information:
Could add tsconfig.json to example-app folder.
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "strict": false,
    "baseUrl": ".",
    "paths": {
      "@ngrx/effects": ["../../modules/effects"],
      "@ngrx/store": ["../../modules/store"],
      "@ngrx/store-devtools": ["../../modules/store-devtools"],
      "@ngrx/router-store": ["../../modules/router-store"],
      "@ngrx/entity": ["../../modules/entity"],
      "@ngrx/schematics": ["../../modules/schematics"],
      "@example-app/*": ["./src/app/*"],
      "ngrx-store-freeze": ["../../projects/ngrx-store-freeze"]
    }
  }
}

```

### PR DESCRIPTION
**Pull request by tja4472**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

vscode reports Typescript problems.

Closes #1592

## What is the new behavior?
No problems.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by tja4472** [comment]
Unfortunately this file has `"strict": true` which is also a problem for example-app.

**Comment by timdeschryver** [comment]
What's the problem with `strict: true`?

**Comment by tja4472** [comment]
Adding the following to tsconfig.app.json
```json
    "strictPropertyInitialization": false,
    "strict": true,
```
and building gives 
```sh
ERROR in projects/example-app/src/app/reducers/index.ts(42,3): error TS2322: Type '(state: State | undefined, action: LayoutActionsUnion) => State' is not assignable to type 'ActionReducer<State, Action>'.
  Types of parameters 'action' and 'action' are incompatible.
    Type 'Action' is not assignable to type 'LayoutActionsUnion'.
      Type 'Action' is not assignable to type 'CloseSidenav'.
        Types of property 'type' are incompatible.
          Type 'string' is not assignable to type 'LayoutActionTypes.CloseSidenav'.
projects/example-app/src/app/reducers/index.ts(48,3): error TS2322: Type '(state: State, action: any) => any' is not assignable to type 'ActionReducer<State, Action>'.
  Types of parameters 'state' and 'state' are incompatible.
    Type 'State | undefined' is not assignable to type 'State'.
      Type 'undefined' is not assignable to type 'State'.
projects/example-app/src/app/core/containers/app.component.ts(47,38): error TS2345: Argument of type '(source$: Observable<State>) => Observable<boolean>' is not assignable to parameter of type 'OperatorFunction<State, boolean>'.
  Types of parameters 'source$' and 'source' are incompatible.
    Type 'import("C:/VSCode/2019/git-hub/platform/node_modules/rxjs/internal/Observable").Observable<import("C:/VSCode/2019/git-hub/platform/projects/example-app/src/app/reducers/index").State>' is not assignable to type 'import("C:/VSCode/2019/git-hub/platform/node_modules/rxjs/internal/Observable").Observable<import("C:/VSCode/2019/git-hub/platform/projects/example-app/src/app/auth/reducers/index").State>'.
      Type 'import("C:/VSCode/2019/git-hub/platform/projects/example-app/src/app/reducers/index").State' is not assignable to type 'import("C:/VSCode/2019/git-hub/platform/projects/example-app/src/app/auth/reducers/index").State'.
        Property 'auth' is missing in type 'State'.
projects/example-app/src/app/books/containers/selected-book-page.component.ts(29,5): error TS2322: Type 'Observable<boolean | "" | null>' is not assignable to type 'Observable<boolean>'.
  Type 'boolean | "" | null' is not assignable to type 'boolean'.
    Type 'null' is not assignable to type 'boolean'.
```

**Comment by timdeschryver** [comment]
🤦‍♂️ Doh, I thought this was just about `ngrx-store-freeze.

I would still like to have `strict` on.

As a workaround, we can solve the typing issue as https://github.com/ngrx/platform/issues/951#issuecomment-425190274

And rewrite the logger as

```ts
export function logger(reducer: ActionReducer<State>): ActionReducer<State> {
  return (state, action) => {
    const result = reducer(state, action);
    console.groupCollapsed(action.type);
    console.log('prev state', state);
    console.log('action', action);
    console.log('next state', result);
    console.groupEnd();

    return result;
  };
}
```

Thoughts?

**Comment by tja4472** [comment]
- Will add the ngrx-store-freeze path in at https://github.com/ngrx/platform/blob/master/tsconfig.json#L37 
- Will fix the `strict` problems.
- This `tsconfig.json` is no longer required.

**Comment by timdeschryver** [comment]
Thanks @tja4472 !

**Pull request merged**
