### PR TITLE
docs: reorganize sidenav into 3 groups

### LINKED ISSUE #2564: Docs: Reorganize sections on homepage/sidenav for packages
## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by jordanpowell88**
Closes #2564

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #2564 

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by alex-okrushko** [comment]
`component-store` is still `State` management, but more focused on `View`. 🤔 
At the same time it's separate from everything that's currently in the `State`.
On the flip side, it would have better visibility there.

@brandonroberts @timdeschryver thoughts?

**Comment by brandonroberts** [comment]
I was thinking the same thing. I think it should go under the State area.

**Comment by jordanpowell88** [comment]
So remove the view “category” all together and move to `state`

**Comment by brandonroberts** [comment]
The `View` category still contains `@ngrx/component`. `@ngrx/component-store` gets moved to `State`

**Pull request merged**
