### PR TITLE
build(example): update dependencies to latest Angular 14-rc version

### LINKED ISSUE #3419: Docs: update example dependencies to latest Angular version
### Information

Docs: Update example dependencies to latest Angular version 14 release

### Documentation page

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by cedricduffournet**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #3419

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by timdeschryver — APPROVED** [review]
👍
image

**Review by markostanimirovic — COMMENTED** [review]
@timdeschryver @cedricduffournet 

Do we need the `boilerplate/cli/package-lock.json` file? Based on the commit history, it was added when the examples were updated to Angular 13 (probably by accident).

**Comment by cedricduffournet** [comment]
@markostanimirovic @timdeschryver yes, I think we can delete it

**Comment by cedricduffournet** [comment]
@markostanimirovic @timdeschryver maybe we can keep it for now as ngrx beta version is not released. So if you try to install example with `npm install` command you'll have dependency error.

Capture d’écran 2022-05-27 à 15 40 29

**Review by markostanimirovic — APPROVED** [review]

**Pull request merged**
