### PR TITLE
Auto cleanup selectors

### PR DESCRIPTION
**Pull request by timdeschryver**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [TODO] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Follow up to #2044 

## What is the new behavior?

After each test, we'll clean the mock selectors. 

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

First commit, shows the failing test
With the introduction of the auto cleanup in the second commit, the test passes

/cc @jtcrowson

### CODE REVIEW

**Comment by jtcrowson** [comment]
Should we also revert #2099?

**Comment by timdeschryver** [comment]
@jtcrowson I would not revert it, but re-word that we're cleaning up for you.

**Comment by jtcrowson** [comment]
I can do that.  We should remove it from the example code and just leave the reworded documentation note, right?

**Comment by timdeschryver** [comment]
Yes, that should be it.
I was waiting on this PR to get accepted first before taking the next steps.

**Pull request merged**
