### PR TITLE
refactor(Example): Unify the form of the actions import name

### PR DESCRIPTION
**Pull request by SangKa**
Hi @brandonroberts 
In the example app, there are two forms for the actions import name, one is pascal and another one is lowercase, as show below:

```ts
// app.ts
import * as layout from '../actions/layout';
import * as Auth from '../../auth/actions/auth';
```
If I was a beginner of ngrx, I couldn't figure out which one was the best practices. It was a little confusing for me.

I suggest to unify the form of the import name, meanwhile I don't know which one is better.

In the [Typed Actions](https://github.com/ngrx/platform/blob/master/docs/store/actions.md#typed-actions) section of the store document, It used the pascal, as show below:

```ts
import { Store, select } from '@ngrx/store';
import { Observable } from 'rxjs/Observable';
import * as Counter from './counter.actions';

interface AppState {
  counter: number;
}

@Component({
  selector: 'my-app',
  template: `
    <button (click)="increment()">Increment</button>
    <button (click)="decrement()">Decrement</button>
    <button (click)="reset()">Reset Counter</button>
    
    <div>Current Count: {{ counter | async }}</div>
  `
})
export class MyAppComponent {
  counter: Observable<number>;

  constructor(private store: Store<AppState>) {
    this.counter = store.pipe(select('counter'));
  }

  increment(){
    this.store.dispatch(new Counter.Increment());
  }

  decrement(){
    this.store.dispatch(new Counter.Decrement());
  }

  reset(){
    this.store.dispatch(new Counter.Reset(3));
  }
}
```

And if we import actions and model for the same entity both, we can just use the lowercase:

```ts
// find-book-page.ts
import * as book from '../actions/book';
import { Book } from '../models/book';
```

So, I need the answer from you guys and then complete this PR that in progress.

### CODE REVIEW

**Comment by SangKa** [comment]
Hi @brandonroberts again.
Although this is a [WIP] PR, but I need your suggestion first.

**Comment by brandonroberts** [comment]
"Best practice" for naming conventions is subjective, but in general I prefer consistency with either choice. For the actions, I'd go with Title/Pascal case for the imports and suffix them with `Actions` (e.g. import * as BookActions from 'somewhere';`. In addition, I'd rename the book model to `BookModel` to also guard against wildcard imports collisions like the one above.

**Comment by SangKa** [comment]
@brandonroberts 
Thanks for your answer that benefits me a lot.
I will make the consistency in this PR and I prefer the way that you handle it.

**Comment by SangKa** [comment]
@brandonroberts Done

**Comment by brandonroberts** [comment]
Changes LGTM, but they highlight another point of confusion. The union exported from https://github.com/ngrx/platform/blob/master/example-app/app/core/actions/layout.ts#L16 is `LayoutActions` also. What about refactoring the union exports to `All`?

**Comment by SangKa** [comment]
How about this?
If need to import the union, take another import  statement and use the alias to avoid the confusion.

```ts
import * as LayoutActions from '../actions/layout';
import { LayoutActions as LayoutActionTypes } from '../actions/layout';
```

**Comment by brandonroberts** [comment]
Layout actions already includes `LayoutActionTypes`

**Comment by SangKa** [comment]
Generally speaking, the union only be imported by the reducer to specify the typed actions, and the import all object (eg `import * as LayoutActions`) is imported by the container component.  They are actually separate.

**Comment by brandonroberts** [comment]
Yes but it's still leads to confusion. I'd rather the imports be distinct

**Comment by SangKa** [comment]
I agree. Now we need a appropriate alias name for union type `LayoutActions`.
How about the `LayoutActionUnion`?

**Comment by brandonroberts** [comment]
I like `LayoutActionsUnion`

**Comment by SangKa** [comment]
That is better. :+1:

**Comment by SangKa** [comment]
hi @brandonroberts 
Does this PR ready to be merged?

**Comment by brandonroberts** [comment]
@SangKa I didn't see where you updated the Unions with the naming scheme we discussed.

**Comment by SangKa** [comment]
All we discussed is for the possibility of the import confusion that doesn't appear in the example for now, and there are nothing to update.

**Comment by brandonroberts** [comment]
Yes, there are no collisions currently but we if want people to use that pattern the example should reflect it

**Comment by SangKa** [comment]
Ok, I got it. I will find a appropriate place to add comment for this.

**Comment by SangKa** [comment]
Already add the comment for explaining, pleases review the description of the comment. Thank you. @brandonroberts

**Comment by brandonroberts** [comment]
@SangKa I would like the union names to actually be changed instead of adding a note about collisions. That way there are no need for the notes.

**Comment by SangKa** [comment]
You means that change [https://github.com/ngrx/platform/blob/master/example-app/app/core/actions/layout.ts#L16](https://github.com/ngrx/platform/blob/master/example-app/app/core/actions/layout.ts#L16) to like this:
`export type LayoutActionsUnion = OpenSidenav | CloseSidenav;`

I hope I got your point.

**Comment by brandonroberts** [comment]
Exactly

**Comment by SangKa** [comment]
Done.

**Comment by brandonroberts** [comment]
Thanks!

**Comment by SangKa** [comment]
My pleasure

**Pull request merged**
