### PR TITLE
refactor(effects): use ObservableNotification instead of Notification, to support RxJS 8

### PR DESCRIPTION
**Pull request by e-oz**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

when using RxJS 8 and importing from "@ngrx/effects":
` Error: export 'Notification' (imported as 'Notification') was not found in 'rxjs' `

## What is the new behavior?

Working code

## Closes

https://github.com/ngrx/platform/discussions/3365

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by timdeschryver — COMMENTED** [review]
While I think the change is good, I think we can't merge this (yet).
There are still a lot of repos (e.g. Angular) that are on RxJS 6.x, adding a reference to `ObservableNotification` will be a breaking change since it's added in 7.x

**Comment by e-oz** [comment]
I could create another PR and copy definition of ObservableNotification from RxJS to effects/index.ts - this way we can avoid import from RxJS, and it will be trivial to replace when world is ready to abandon RxJS 6.

**Comment by e-oz** [comment]
e2e-affected failed because of timeout - please let me know if it's a legit issue or can be ignored.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks @e-oz!

**Pull request merged**
